apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: httpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  # namespace: ms
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: "appache"
    port: 80
    targetPort: 80
    nodePort: 30009
